version: '3.7'

services:
  # web:
    # build: .
    # command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # volumes:
    #   - ./app:/app
    # ports:
    #   - 8000:8000
    # depends_on:
    #   - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
